### ISSUE TITLE
React does not recognize the dependsOnValue

### ISSUE THREAD

**Issue by llioor** [marmelab/aor-dependent-input#23]
Hi,
I think it is an issue with React 16 but I'm not sure.
I have this code:

React does not recognize the `dependsOnValue` prop on a DOM element
```
 <DependentInput dependsOn="country_id">
              <StatesSelectInput source="state_id"/>
            </DependentInput>
```

In my console I have this error:
```
Warning: React does not recognize the `dependsOnValue` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `dependsonvalue` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
```

The error is clear, it is not urgent but just annoying.
Thanks.

**Comment by afilp** [comment]
@djhi Does it need `sanitizeProps` I assume?

**Comment by afilp** [comment]
@djhi Is it known that `dependentInput` is not functional in `next`? I am not sure if I should create an issue here or in `admin-on-rest`. I thought it is more suitable there, as everything is there now:

https://github.com/marmelab/admin-on-rest/issues/1607

If you want me to create the issue here, please let me know, I am really very stuck with this...

**Comment by fzaninotto** [comment]
Fixed by https://github.com/marmelab/admin-on-rest/pull/1675, let's track the issue there.

**Comment by khukeke** [comment]
> Fixed by https://github.com/marmelab/admin-on-rest/pull/1675, let's track the issue there.

@fzaninotto  this url is 404.

**Comment by fzaninotto** [comment]
try https://github.com/marmelab/react-admin/pull/1675
